name: Continuous deployment
on: 
  pull_request:
    branches: 
      - main
      
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **/*.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps: 
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado
          path: downloaded_artifact  # Opcional: define um diretório de destino

      - name: Display structure of downloaded files
        run: ls -R downloaded_artifact  # Listar os arquivos baixados
